version: '3.8'

services:
  frontend:
    build:
      context: frontend_app
      dockerfile: Dockerfile
    ports:
      - "8081:80"
  backend:
    build:
      context: python_app
      dockerfile: Dockerfile
